# Generated by Django 5.2 on 2025-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_url', models.URLField()),
                ('pause_start', models.DateField(auto_now_add=True)),
                ('pause_end', models.DateField(null=True)),
                ('feedback', models.CharField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_num', models.IntegerField()),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField(null=True)),
                ('points', models.BigIntegerField()),
                ('deadline', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('track', models.CharField(primary_key=True, serialize=False)),
            ],
        ),
    ]
