# Generated by Django 5.2 on 2025-04-15 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissions',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.tasks'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.tasks'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.tracks'),
        ),
    ]
