# Generated by Django 5.2 on 2025-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track',
            field=models.CharField(default='Vidyaratna1', primary_key=True, serialize=False),
        ),
    ]
