# Generated by Django 5.2 on 2025-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_tracks_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
