# Generated by Django 5.2 on 2025-04-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_tracks_track'),
        ('members', '0002_alter_members_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.tracks'),
        ),
    ]
