# Generated by Django 5.2 on 2025-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='discord',
            field=models.TextField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='github',
            field=models.TextField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='name',
            field=models.TextField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
